package errs

// definitions is the single source of truth for every MAS-NNNN code
// (Constitution Art. V.2). Allocation blocks are specified in
// specs/001-mvp-core/design-hld.md §7.1.
//
// Rules enforced by tests in this package:
//   - codes are unique and match ^MAS-[1-9][0-9]{3}$
//   - MessageEN and MessageZH carry the same fmt verb sequence
//   - no field is empty
var definitions = []Definition{
	// ── 1xxx · configuration & request ──────────────────────────────────────
	{"MAS-1001", "ConfigInvalid", SeverityError,
		"configuration file %q could not be parsed", "配置文件 %q 无法解析",
		"Check the YAML syntax; run `mas doctor --config <path>` for a precise location.",
		"检查 YAML 语法；执行 `mas doctor --config <path>` 可定位到具体位置。"},
	{"MAS-1002", "ConfigUnknownField", SeverityError,
		"unknown configuration field %q", "未知的配置字段 %q",
		"Remove the field or check docs/en/configuration.md for the correct name.",
		"删除该字段，或对照 docs/zh/configuration.md 核对正确名称。"},
	{"MAS-1003", "ConfigValidation", SeverityError,
		"configuration is invalid at %s: %s", "配置在 %s 处非法：%s",
		"Correct the named path; every constraint is listed in docs/en/configuration.md.",
		"修正指出的配置路径；全部约束见 docs/zh/configuration.md。"},
	{"MAS-1004", "ConfigNotFound", SeverityError,
		"no configuration file found in %v", "在 %v 中未找到配置文件",
		"Pass --config, set MAS_CONFIG, or place mas.yaml in the working directory.",
		"使用 --config 指定、设置 MAS_CONFIG，或在工作目录放置 mas.yaml。"},
	{"MAS-1005", "TargetUnknown", SeverityError,
		"unknown target %q", "未知目标 %q",
		"Run `mas targets` to list configured targets.",
		"执行 `mas targets` 查看已配置的目标。"},
	{"MAS-1006", "SecretUnresolvable", SeverityError,
		"secret reference %q could not be resolved", "密钥引用 %q 无法解析",
		"Ensure the referenced environment variable or file exists and is readable.",
		"确认被引用的环境变量或文件存在且可读。"},
	{"MAS-1007", "RequestInvalid", SeverityError,
		"diagnostic request is invalid: %s", "诊断请求非法：%s",
		"Correct the request; `mas diagnose --help` documents every field.",
		"修正请求；`mas diagnose --help` 说明了每个字段。"},
	{"MAS-1008", "EnvUnknown", SeverityError,
		"target %q references unknown environment %q", "目标 %q 引用了未知环境 %q",
		"Declare the environment under `envs:` in the configuration file.",
		"在配置文件的 `envs:` 下声明该环境。"},
	{"MAS-1010", "WindowInvalid", SeverityError,
		"invalid time window: %s", "时间窗口非法：%s",
		"Use --since (e.g. 1h) or an explicit --from/--to pair with from < to.",
		"使用 --since（如 1h），或显式给出满足 from < to 的 --from/--to。"},
	{"MAS-1011", "ModeInvalid", SeverityError,
		"invalid mode %q", "运行模式 %q 非法",
		"Use `offline` (telemetry only) or `online` (also reads the live environment).",
		"使用 `offline`（仅遥测）或 `online`（同时读取实时环境）。"},
	{"MAS-1012", "TelemetrySourceUnknown", SeverityError,
		"unknown telemetry source %q", "未知遥测数据源 %q",
		"Declare the source under `telemetry.metrics` or `telemetry.logs`.",
		"在 `telemetry.metrics` 或 `telemetry.logs` 下声明该数据源。"},

	// ── 2xxx · LLM providers ────────────────────────────────────────────────
	{"MAS-2001", "ProviderUnavailable", SeverityError,
		"LLM provider %q is unavailable", "LLM 供应商 %q 不可用",
		"Check network reachability and base_url; the run continues with deterministic findings only.",
		"检查网络连通性与 base_url；本次运行将仅输出确定性结论。"},
	{"MAS-2002", "ProviderAuthFailed", SeverityError,
		"LLM provider %q rejected the credentials", "LLM 供应商 %q 拒绝了凭据",
		"Verify llm.api_key and that the key has access to the requested model.",
		"确认 llm.api_key 有效，且该密钥有权访问所请求的模型。"},
	{"MAS-2003", "ProviderRateLimited", SeverityError,
		"LLM provider %q rate-limited the request", "LLM 供应商 %q 对请求进行了限流",
		"Retry later, lower run.budget, or use a model with higher quota.",
		"稍后重试、降低 run.budget，或改用配额更高的模型。"},
	{"MAS-2004", "ToolCallUnparseable", SeverityError,
		"model produced an unusable tool call for %q: %s", "模型为 %q 产出了无法使用的工具调用：%s",
		"The agent retries with a repair prompt; persistent failures suggest a weaker model.",
		"Agent 会以修复提示重试；持续失败通常说明模型能力不足。"},
	{"MAS-2005", "ProviderUnknown", SeverityError,
		"unknown LLM provider %q", "未知 LLM 供应商 %q",
		"Use one of: mock, anthropic, openai.",
		"请使用：mock、anthropic、openai 之一。"},
	{"MAS-2006", "ModelRefused", SeverityWarn,
		"model declined to answer: %s", "模型拒绝回答：%s",
		"Rephrase the symptom, or inspect the prompt with --log-level debug.",
		"重新描述症状，或使用 --log-level debug 检查提示词。"},
	{"MAS-2007", "TokenBudgetExceeded", SeverityWarn,
		"token budget exhausted after %d tokens", "token 预算在 %d tokens 后耗尽",
		"Raise run.budget.max_tokens, or accept the truncated analysis.",
		"提高 run.budget.max_tokens，或接受被截断的分析结果。"},
	{"MAS-2008", "ProviderResponseMalformed", SeverityError,
		"LLM provider %q returned a malformed response: %s", "LLM 供应商 %q 返回了格式错误的响应：%s",
		"Confirm base_url points at a compatible API; enable debug logging to inspect the body.",
		"确认 base_url 指向兼容的 API；开启 debug 日志可查看响应体。"},
	{"MAS-2009", "MockScriptExhausted", SeverityError,
		"mock provider script has no reply for turn %d", "mock provider 脚本在第 %d 轮没有可用回复",
		"Extend the mock script; this only occurs in tests and demos.",
		"扩展 mock 脚本；该情况仅出现在测试与演示中。"},

	// ── 3xxx · agents & orchestration ───────────────────────────────────────
	{"MAS-3001", "TopologyUnknown", SeverityError,
		"unknown topology %q", "未知拓扑 %q",
		"Run `mas topologies` to list the registered topologies.",
		"执行 `mas topologies` 查看已注册的拓扑。"},
	{"MAS-3002", "OrchestratorFailed", SeverityError,
		"topology %q failed: %s", "拓扑 %q 执行失败：%s",
		"Inspect the run record with `mas replay <run-id> --steps`.",
		"使用 `mas replay <run-id> --steps` 检查运行记录。"},
	{"MAS-3003", "AgentFailed", SeverityError,
		"agent %q failed: %s", "Agent %q 执行失败：%s",
		"Inspect the failing step in the run record; the run reports partial findings.",
		"在运行记录中检查失败步骤；本次运行会输出部分结论。"},
	{"MAS-3005", "StepBudgetExceeded", SeverityWarn,
		"step budget of %d exhausted", "步数预算 %d 已耗尽",
		"Raise run.budget.max_steps if the analysis was cut short.",
		"若分析被过早截断，可提高 run.budget.max_steps。"},
	{"MAS-3006", "WallBudgetExceeded", SeverityWarn,
		"wall-clock budget of %s exhausted", "墙钟预算 %s 已耗尽",
		"Raise run.budget.max_wall, or narrow the time window.",
		"提高 run.budget.max_wall，或收窄时间窗口。"},
	{"MAS-3007", "ToolCallBudgetExceeded", SeverityWarn,
		"tool-call budget of %d exhausted", "工具调用预算 %d 已耗尽",
		"Raise run.budget.max_tool_calls if evidence collection was cut short.",
		"若证据采集被过早截断，可提高 run.budget.max_tool_calls。"},
	{"MAS-3010", "NoProgress", SeverityWarn,
		"agent %q made no progress for %d consecutive steps", "Agent %q 连续 %d 步没有进展",
		"The run concludes with what was gathered; consider a stronger model.",
		"本次运行以已收集内容作结；可考虑更换更强的模型。"},

	// ── 4xxx · collectors, adapters & source ────────────────────────────────
	{"MAS-4001", "MetricsUnreachable", SeverityError,
		"metrics source %q is unreachable: %s", "指标数据源 %q 不可达：%s",
		"Check telemetry.metrics[].url and network policy; analysis continues without metrics.",
		"检查 telemetry.metrics[].url 与网络策略；分析将在无指标的情况下继续。"},
	{"MAS-4002", "MetricsStatus", SeverityError,
		"metrics source %q returned HTTP %d", "指标数据源 %q 返回 HTTP %d",
		"Verify the endpoint path and credentials for the metrics source.",
		"核对该指标数据源的端点路径与凭据。"},
	{"MAS-4003", "MetricsMalformed", SeverityError,
		"metrics source %q returned a malformed response: %s", "指标数据源 %q 返回了格式错误的响应：%s",
		"Confirm the URL points at a Prometheus-compatible HTTP API v1.",
		"确认该 URL 指向 Prometheus 兼容的 HTTP API v1。"},
	{"MAS-4004", "MetricsQueryRejected", SeverityError,
		"metrics query rejected: %s", "指标查询被拒绝：%s",
		"The PromQL was refused by the server; check the knowledge pack's signal definition.",
		"服务端拒绝了该 PromQL；请检查知识包中的信号定义。"},
	{"MAS-4005", "MetricsTruncated", SeverityWarn,
		"metrics result truncated at %d samples", "指标结果在 %d 个样本处被截断",
		"Narrow the window or raise telemetry.metrics[].max_samples.",
		"收窄时间窗口，或提高 telemetry.metrics[].max_samples。"},
	{"MAS-4101", "LogsUnreachable", SeverityError,
		"log source %q is unreachable: %s", "日志数据源 %q 不可达：%s",
		"Check telemetry.logs[].url; analysis continues without logs.",
		"检查 telemetry.logs[].url；分析将在无日志的情况下继续。"},
	{"MAS-4102", "LogsStatus", SeverityError,
		"log source %q returned HTTP %d", "日志数据源 %q 返回 HTTP %d",
		"Verify the endpoint path and credentials for the log source.",
		"核对该日志数据源的端点路径与凭据。"},
	{"MAS-4103", "LogsMalformed", SeverityError,
		"log source %q returned a malformed response: %s", "日志数据源 %q 返回了格式错误的响应：%s",
		"Confirm the URL points at a Loki-compatible HTTP API v1.",
		"确认该 URL 指向 Loki 兼容的 HTTP API v1。"},
	{"MAS-4104", "LogsQueryRejected", SeverityError,
		"log query rejected: %s", "日志查询被拒绝：%s",
		"The LogQL was refused by the server; check the knowledge pack's log pattern.",
		"服务端拒绝了该 LogQL；请检查知识包中的日志模式定义。"},
	{"MAS-4105", "LogsTruncated", SeverityWarn,
		"log result truncated at %d lines", "日志结果在 %d 行处被截断",
		"Narrow the window or raise telemetry.logs[].max_lines.",
		"收窄时间窗口，或提高 telemetry.logs[].max_lines。"},
	{"MAS-4201", "KubeForbidden", SeverityWarn,
		"Kubernetes denied read access to %s: %s", "Kubernetes 拒绝了对 %s 的读取：%s",
		"Grant the service account `get`/`list` on that resource; the run continues with a gap.",
		"为该 ServiceAccount 授予对应资源的 `get`/`list` 权限；本次运行将带缺口继续。"},
	{"MAS-4202", "KubeNoCredentials", SeverityWarn,
		"no Kubernetes credentials available for environment %q", "环境 %q 没有可用的 Kubernetes 凭据",
		"Set envs.<name>.kubeconfig, or run in-cluster with a service account.",
		"设置 envs.<name>.kubeconfig，或以带 ServiceAccount 的集群内方式运行。"},
	{"MAS-4203", "KubeUnreachable", SeverityError,
		"Kubernetes API server is unreachable: %s", "Kubernetes API Server 不可达：%s",
		"Check the server URL, CA bundle and network policy.",
		"检查 API Server 地址、CA 证书与网络策略。"},
	{"MAS-4204", "KubeNotFound", SeverityWarn,
		"Kubernetes object not found: %s", "Kubernetes 对象不存在：%s",
		"Check the namespace and selector on the target definition.",
		"检查目标定义中的命名空间与选择器。"},
	{"MAS-4205", "KubeMalformed", SeverityError,
		"Kubernetes API returned a malformed response: %s", "Kubernetes API 返回了格式错误的响应：%s",
		"Confirm the URL points at a Kubernetes API server.",
		"确认该 URL 指向 Kubernetes API Server。"},
	{"MAS-4301", "HostCommandFailed", SeverityWarn,
		"host command %q failed: %s", "主机命令 %q 执行失败：%s",
		"Check that the command exists and the process has permission to run it.",
		"确认该命令存在，且当前进程有权执行它。"},
	{"MAS-4302", "HostBinaryNotFound", SeverityWarn,
		"binary %q not found on PATH", "PATH 中未找到可执行文件 %q",
		"Install the tool in the image or on the host, or omit checks that need it.",
		"在镜像或主机上安装该工具，或跳过依赖它的检查。"},
	{"MAS-4303", "HostUnsupported", SeverityWarn,
		"host inspection %q is not supported on %s", "主机巡检 %q 在 %s 上不受支持",
		"This check is skipped; it is available on Linux hosts.",
		"该检查将被跳过；它仅在 Linux 主机上可用。"},
	{"MAS-4401", "SourceFellBackToMirror", SeverityWarn,
		"source for %q unreachable over the network; using local mirror %s", "%q 的源码网络不可达；改用本地镜像 %s",
		"Expected in air-gapped environments; verify the mirror matches the deployed version.",
		"离网环境下属预期行为；请确认镜像版本与部署版本一致。"},
	{"MAS-4402", "SourceUnavailable", SeverityWarn,
		"no source available for %q: %s", "%q 无可用源码：%s",
		"Configure source.repos or source.mirrors; source-based analysis is skipped.",
		"配置 source.repos 或 source.mirrors；基于源码的分析将被跳过。"},
	{"MAS-4403", "SourceRefNotFound", SeverityWarn,
		"source ref %q not found for %q", "%q 的源码 ref %q 不存在",
		"Check the target's version, or fetch the default branch instead.",
		"检查目标版本，或改为拉取默认分支。"},
	{"MAS-4404", "SourceSearchInvalid", SeverityError,
		"source search pattern is invalid: %s", "源码检索模式非法：%s",
		"Use a valid RE2 regular expression.",
		"请使用合法的 RE2 正则表达式。"},
	{"MAS-4405", "SourceToolMissing", SeverityWarn,
		"git is not available; source acquisition is disabled", "git 不可用；源码获取功能被禁用",
		"Install git in the image or on the host to enable source-based analysis.",
		"在镜像或主机上安装 git 以启用基于源码的分析。"},

	// ── 5xxx · knowledge & rules ────────────────────────────────────────────
	{"MAS-5001", "PackSchemaViolation", SeverityError,
		"knowledge pack %s is invalid at %s: %s", "知识包 %s 在 %s 处非法：%s",
		"Fix the pack against docs/en/knowledge-packs.md, then reload.",
		"对照 docs/zh/knowledge-packs.md 修正该包后重新加载。"},
	{"MAS-5002", "PackDuplicate", SeverityError,
		"duplicate knowledge pack id %q", "知识包 id %q 重复",
		"Pack ids must be unique across embedded and user pack directories.",
		"知识包 id 在内置目录与用户目录之间必须唯一。"},
	{"MAS-5003", "PackNotFound", SeverityWarn,
		"no knowledge pack for middleware %q", "中间件 %q 没有对应的知识包",
		"Add a pack under knowledge.pack_dirs; analysis proceeds with generic checks only.",
		"在 knowledge.pack_dirs 下新增知识包；否则仅执行通用检查。"},
	{"MAS-5004", "PackVersionRangeInvalid", SeverityError,
		"knowledge pack %s has an invalid version range %q", "知识包 %s 的版本区间 %q 非法",
		"Use a range such as \">=5.0\", \"<7\", or \">=5.0 <8.0\".",
		"请使用形如 \">=5.0\"、\"<7\"、\">=5.0 <8.0\" 的区间。"},
	{"MAS-5005", "PackReadFailed", SeverityError,
		"knowledge pack %s could not be read: %s", "知识包 %s 无法读取：%s",
		"Check file permissions on the pack directory.",
		"检查知识包目录的文件权限。"},
	{"MAS-5010", "ExpressionCompile", SeverityError,
		"playbook %s step %s has an invalid expression: %s", "剧本 %s 的步骤 %s 表达式非法：%s",
		"Fix the expression; only step results and helper functions are in scope.",
		"修正该表达式；作用域内只有步骤结果与辅助函数。"},
	{"MAS-5011", "ExpressionType", SeverityError,
		"playbook %s step %s expression did not evaluate to a boolean: %s", "剧本 %s 的步骤 %s 表达式未求值为布尔：%s",
		"An `evaluate` expression must yield true or false.",
		"`evaluate` 表达式必须求值为 true 或 false。"},
	{"MAS-5012", "SignalUnknown", SeverityError,
		"playbook %s references unknown signal %q", "剧本 %s 引用了未知信号 %q",
		"Declare the signal under `signals:` in the same knowledge pack.",
		"在同一知识包的 `signals:` 下声明该信号。"},
	{"MAS-5013", "PlaybookBudgetExceeded", SeverityWarn,
		"playbook %s exceeded its step budget of %d", "剧本 %s 超出其步数预算 %d",
		"Split the playbook, or raise run.budget.max_steps.",
		"拆分该剧本，或提高 run.budget.max_steps。"},
	{"MAS-5014", "PlaybookStepInvalid", SeverityError,
		"playbook %s step %s is invalid: %s", "剧本 %s 的步骤 %s 非法：%s",
		"A step must declare exactly one of collect, evaluate or conclude.",
		"每个步骤必须且只能声明 collect、evaluate、conclude 之一。"},

	// ── 6xxx · storage ──────────────────────────────────────────────────────
	{"MAS-6001", "RunNotFound", SeverityError,
		"run %q not found", "运行记录 %q 不存在",
		"Run `mas runs` to list stored runs.",
		"执行 `mas runs` 查看已存储的运行记录。"},
	{"MAS-6002", "RunWriteFailed", SeverityError,
		"could not persist run %q: %s", "无法持久化运行记录 %q：%s",
		"Check that store.dir exists and is writable.",
		"确认 store.dir 存在且可写。"},
	{"MAS-6003", "RunCorrupt", SeverityError,
		"run %q is corrupt: %s", "运行记录 %q 已损坏：%s",
		"The record failed its integrity check and cannot be replayed.",
		"该记录未通过完整性校验，无法重放。"},
	{"MAS-6004", "RunStoreUnavailable", SeverityError,
		"run store is unavailable: %s", "运行存储不可用：%s",
		"Check store.type and store.dir.",
		"检查 store.type 与 store.dir。"},

	// ── 7xxx · API & CLI ────────────────────────────────────────────────────
	{"MAS-7001", "BadRequest", SeverityError,
		"bad request: %s", "请求非法：%s",
		"See docs/en/user-manual.md for the request schema.",
		"请求结构见 docs/zh/user-manual.md。"},
	{"MAS-7002", "MethodNotAllowed", SeverityError,
		"method %s not allowed on %s", "%s 方法不允许用于 %s",
		"Use the documented method for this endpoint.",
		"请对该端点使用文档规定的方法。"},
	{"MAS-7003", "ServerInternal", SeverityError,
		"internal server error: %s", "服务器内部错误：%s",
		"Check the server logs for the correlated run_id.",
		"根据关联的 run_id 检查服务端日志。"},
	{"MAS-7005", "ServerStartFailed", SeverityError,
		"server failed to start on %s: %s", "服务器在 %s 上启动失败：%s",
		"Check that the address is free and the process may bind it.",
		"确认该地址未被占用且进程有权绑定。"},
	{"MAS-7404", "NotFound", SeverityError,
		"not found: %s", "未找到：%s",
		"Check the identifier in the request path.",
		"检查请求路径中的标识符。"},

	// ── 8xxx · safety ───────────────────────────────────────────────────────
	{"MAS-8001", "MutatingRefused", SeverityError,
		"refused: %s would mutate the target environment", "已拒绝：%s 会变更目标环境",
		"MAS-Turbo is read-only by constitution; perform the action yourself if intended.",
		"MAS-Turbo 依据宪章只读；如确需执行，请由人工操作。"},
	{"MAS-8002", "CommandNotAllowed", SeverityError,
		"refused: %s is not on the read-only allow-list", "已拒绝：%s 不在只读白名单内",
		"Add the capability through a knowledge pack and a specification change, not at runtime.",
		"通过知识包与规格变更来新增该能力，而不是在运行期放行。"},
	{"MAS-8003", "PathNotAllowed", SeverityError,
		"refused: %s %s is not an allow-listed read path", "已拒绝：%s %s 不是白名单内的只读路径",
		"Only documented read endpoints may be called.",
		"只能调用文档中列明的只读端点。"},
	{"MAS-8005", "ArgumentRejected", SeverityError,
		"refused: argument %q rejected (%s)", "已拒绝：参数 %q 被拒（%s）",
		"Arguments may not contain shell metacharacters, traversal or mutating verbs.",
		"参数中不得包含 Shell 元字符、路径穿越或变更类动词。"},
	{"MAS-8006", "ToolNotRegistered", SeverityError,
		"refused: tool %q is not registered", "已拒绝：工具 %q 未注册",
		"Run `mas tools` to list the available capabilities.",
		"执行 `mas tools` 查看可用能力。"},
	{"MAS-8010", "CeilingExceeded", SeverityError,
		"refused: %s exceeds the configured ceiling (%s)", "已拒绝：%s 超出配置的上限（%s）",
		"Raise the ceiling in `safety:` only if you understand the resource cost.",
		"仅在确知资源代价的前提下，才在 `safety:` 中提高该上限。"},

	// ── 9xxx · internal ─────────────────────────────────────────────────────
	{"MAS-9001", "InvariantViolated", SeverityError,
		"internal invariant violated: %s", "内部不变量被破坏：%s",
		"This is a defect; please report it with the run record.",
		"这是缺陷；请附带运行记录反馈给我们。"},
	{"MAS-9002", "Unexpected", SeverityError,
		"unexpected internal error: %s", "未预期的内部错误：%s",
		"This is a defect; please report it with the run record.",
		"这是缺陷；请附带运行记录反馈给我们。"},
}
