package errs

// definitions is the single source of truth for every MAS-NNNN code
// (Constitution Art. V.2). Allocation blocks are specified in
// specs/001-mvp-core/design-hld.md §7.1.
//
// Rules enforced by tests in this package:
//   - codes are unique and match ^MAS-[1-9][0-9]{3}$
//   - MessageEN and MessageZH carry the same fmt verb sequence
//   - no field is empty
var definitions = []Definition{
	// ── 1xxx · configuration & request ──────────────────────────────────────
	{"MAS-1001", "ConfigInvalid", SeverityError,
		"configuration file %q could not be parsed", "配置文件 %q 无法解析",
		"Check the YAML syntax; run `mas doctor --config <path>` for a precise location.",
		"检查 YAML 语法；执行 `mas doctor --config <path>` 可定位到具体位置。"},
	{"MAS-1002", "ConfigUnknownField", SeverityError,
		"unknown configuration field %q", "未知的配置字段 %q",
		"Remove the field or check docs/en/configuration.md for the correct name.",
		"删除该字段，或对照 docs/zh/configuration.md 核对正确名称。"},
	{"MAS-1003", "ConfigValidation", SeverityError,
		"configuration is invalid at %s: %s", "配置在 %s 处非法：%s",
		"Correct the named path; every constraint is listed in docs/en/configuration.md.",
		"修正指出的配置路径；全部约束见 docs/zh/configuration.md。"},
	{"MAS-1004", "ConfigNotFound", SeverityError,
		"no configuration file found in %v", "在 %v 中未找到配置文件",
		"Pass --config, set MAS_CONFIG, or place mas.yaml in the working directory.",
		"使用 --config 指定、设置 MAS_CONFIG，或在工作目录放置 mas.yaml。"},
	{"MAS-1005", "TargetUnknown", SeverityError,
		"unknown target %q", "未知目标 %q",
		"Run `mas targets` to list configured targets.",
		"执行 `mas targets` 查看已配置的目标。"},
	{"MAS-1006", "SecretUnresolvable", SeverityError,
		"secret reference %q could not be resolved", "密钥引用 %q 无法解析",
		"Ensure the referenced environment variable or file exists and is readable.",
		"确认被引用的环境变量或文件存在且可读。"},
	{"MAS-1007", "RequestInvalid", SeverityError,
		"diagnostic request is invalid: %s", "诊断请求非法：%s",
		"Correct the request; `mas diagnose --help` documents every field.",
		"修正请求；`mas diagnose --help` 说明了每个字段。"},
	{"MAS-1008", "EnvUnknown", SeverityError,
		"target %q references unknown environment %q", "目标 %q 引用了未知环境 %q",
		"Declare the environment under `envs:` in the configuration file.",
		"在配置文件的 `envs:` 下声明该环境。"},
	{"MAS-1013", "TenancyInconsistent", SeverityError,
		"tenancy configuration is inconsistent: %s", "租户配置不自洽：%s",
		"Naming a tenant on any target makes the whole configuration multi-tenant. Then every target needs one, every API credential needs the tenants it may act for, and every tenant a credential names must exist.",
		"只要在任何一个目标上写下 tenant，整份配置就是多租户的。此时每个目标都需要 tenant，每个 API 凭据都需要写明它能代表哪些租户，且凭据写下的每个租户都必须真实存在。"},
	{"MAS-1010", "WindowInvalid", SeverityError,
		"invalid time window: %s", "时间窗口非法：%s",
		"Use --since (e.g. 1h) or an explicit --from/--to pair with from < to.",
		"使用 --since（如 1h），或显式给出满足 from < to 的 --from/--to。"},
	{"MAS-1011", "ModeInvalid", SeverityError,
		"invalid mode %q", "运行模式 %q 非法",
		"Use `offline` (telemetry only) or `online` (also reads the live environment).",
		"使用 `offline`（仅遥测）或 `online`（同时读取实时环境）。"},
	{"MAS-1012", "TelemetrySourceUnknown", SeverityError,
		"unknown telemetry source %q", "未知遥测数据源 %q",
		"Declare the source under `telemetry.metrics` or `telemetry.logs`.",
		"在 `telemetry.metrics` 或 `telemetry.logs` 下声明该数据源。"},

	// ── 2xxx · LLM providers ────────────────────────────────────────────────
	{"MAS-2001", "ProviderUnavailable", SeverityError,
		"LLM provider %q is unavailable", "LLM 供应商 %q 不可用",
		"Check network reachability and base_url; the run continues with deterministic findings only.",
		"检查网络连通性与 base_url；本次运行将仅输出确定性结论。"},
	{"MAS-2002", "ProviderAuthFailed", SeverityError,
		"LLM provider %q rejected the credentials", "LLM 供应商 %q 拒绝了凭据",
		"Verify llm.api_key and that the key has access to the requested model.",
		"确认 llm.api_key 有效，且该密钥有权访问所请求的模型。"},
	{"MAS-2003", "ProviderRateLimited", SeverityError,
		"LLM provider %q rate-limited the request", "LLM 供应商 %q 对请求进行了限流",
		"Retry later, lower run.budget, or use a model with higher quota.",
		"稍后重试、降低 run.budget，或改用配额更高的模型。"},
	{"MAS-2004", "ToolCallUnparseable", SeverityError,
		"model produced an unusable tool call for %q: %s", "模型为 %q 产出了无法使用的工具调用：%s",
		"The agent retries with a repair prompt; persistent failures suggest a weaker model.",
		"Agent 会以修复提示重试；持续失败通常说明模型能力不足。"},
	{"MAS-2005", "ProviderUnknown", SeverityError,
		"unknown LLM provider %q", "未知 LLM 供应商 %q",
		"Use one of: mock, anthropic, openai.",
		"请使用：mock、anthropic、openai 之一。"},
	{"MAS-2006", "ModelRefused", SeverityWarn,
		"model declined to answer: %s", "模型拒绝回答：%s",
		"Rephrase the symptom, or inspect the prompt with --log-level debug.",
		"重新描述症状，或使用 --log-level debug 检查提示词。"},
	{"MAS-2007", "TokenBudgetExceeded", SeverityWarn,
		"token budget exhausted after %d tokens", "token 预算在 %d tokens 后耗尽",
		"Raise run.budget.max_tokens, or accept the truncated analysis.",
		"提高 run.budget.max_tokens，或接受被截断的分析结果。"},
	{"MAS-2008", "ProviderResponseMalformed", SeverityError,
		"LLM provider %q returned a malformed response: %s", "LLM 供应商 %q 返回了格式错误的响应：%s",
		"Confirm base_url points at a compatible API; enable debug logging to inspect the body.",
		"确认 base_url 指向兼容的 API；开启 debug 日志可查看响应体。"},
	{"MAS-2009", "MockScriptExhausted", SeverityError,
		"mock provider script has no reply for turn %d", "mock provider 脚本在第 %d 轮没有可用回复",
		"Extend the mock script; this only occurs in tests and demos.",
		"扩展 mock 脚本；该情况仅出现在测试与演示中。"},
	{"MAS-2010", "CitationUnresolved", SeverityWarn,
		"the model cited %d reference(s) that this run did not collect: %s",
		"模型引用了本次运行并未采集到的 %d 条引用：%s",
		"The unresolved references were dropped from the report. A model that cites evidence it was not given is guessing; check the transcript for the role that produced them.",
		"这些无法解析的引用已从报告中剔除。模型引用了未曾提供给它的证据，说明它在猜；请在转录中查看是哪个角色产出的。"},

	// ── 3xxx · agents & orchestration ───────────────────────────────────────
	{"MAS-3001", "TopologyUnknown", SeverityError,
		"unknown topology %q", "未知拓扑 %q",
		"Run `mas topologies` to list the registered topologies.",
		"执行 `mas topologies` 查看已注册的拓扑。"},
	{"MAS-3002", "OrchestratorFailed", SeverityError,
		"topology %q failed: %s", "拓扑 %q 执行失败：%s",
		"Inspect the run record with `mas replay <run-id> --steps`.",
		"使用 `mas replay <run-id> --steps` 检查运行记录。"},
	{"MAS-3003", "AgentFailed", SeverityError,
		"agent %q failed: %s", "Agent %q 执行失败：%s",
		"Inspect the failing step in the run record; the run reports partial findings.",
		"在运行记录中检查失败步骤；本次运行会输出部分结论。"},
	{"MAS-3005", "StepBudgetExceeded", SeverityWarn,
		"step budget of %d exhausted", "步数预算 %d 已耗尽",
		"Raise run.budget.max_steps if the analysis was cut short.",
		"若分析被过早截断，可提高 run.budget.max_steps。"},
	{"MAS-3006", "WallBudgetExceeded", SeverityWarn,
		"wall-clock budget of %s exhausted", "墙钟预算 %s 已耗尽",
		"Raise run.budget.max_wall, or narrow the time window.",
		"提高 run.budget.max_wall，或收窄时间窗口。"},
	{"MAS-3007", "ToolCallBudgetExceeded", SeverityWarn,
		"tool-call budget of %d exhausted", "工具调用预算 %d 已耗尽",
		"Raise run.budget.max_tool_calls if evidence collection was cut short.",
		"若证据采集被过早截断，可提高 run.budget.max_tool_calls。"},
	{"MAS-3010", "NoProgress", SeverityWarn,
		"agent %q made no progress for %d consecutive steps", "Agent %q 连续 %d 步没有进展",
		"The run concludes with what was gathered; consider a stronger model.",
		"本次运行以已收集内容作结；可考虑更换更强的模型。"},

	// ── 4xxx · collectors, adapters & source ────────────────────────────────
	{"MAS-4001", "MetricsUnreachable", SeverityError,
		"metrics source %q is unreachable: %s", "指标数据源 %q 不可达：%s",
		"Check telemetry.metrics[].url and network policy; analysis continues without metrics.",
		"检查 telemetry.metrics[].url 与网络策略；分析将在无指标的情况下继续。"},
	{"MAS-4002", "MetricsStatus", SeverityError,
		"metrics source %q returned HTTP %d", "指标数据源 %q 返回 HTTP %d",
		"Verify the endpoint path and credentials for the metrics source.",
		"核对该指标数据源的端点路径与凭据。"},
	{"MAS-4003", "MetricsMalformed", SeverityError,
		"metrics source %q returned a malformed response: %s", "指标数据源 %q 返回了格式错误的响应：%s",
		"Confirm the URL points at a Prometheus-compatible HTTP API v1.",
		"确认该 URL 指向 Prometheus 兼容的 HTTP API v1。"},
	{"MAS-4004", "MetricsQueryRejected", SeverityError,
		"metrics query rejected: %s", "指标查询被拒绝：%s",
		"The PromQL was refused by the server; check the knowledge pack's signal definition.",
		"服务端拒绝了该 PromQL；请检查知识包中的信号定义。"},
	{"MAS-4005", "MetricsTruncated", SeverityWarn,
		"metrics result truncated at %d samples", "指标结果在 %d 个样本处被截断",
		"Narrow the window or raise telemetry.metrics[].max_samples.",
		"收窄时间窗口，或提高 telemetry.metrics[].max_samples。"},
	{"MAS-4101", "LogsUnreachable", SeverityError,
		"log source %q is unreachable: %s", "日志数据源 %q 不可达：%s",
		"Check telemetry.logs[].url; analysis continues without logs.",
		"检查 telemetry.logs[].url；分析将在无日志的情况下继续。"},
	{"MAS-4102", "LogsStatus", SeverityError,
		"log source %q returned HTTP %d", "日志数据源 %q 返回 HTTP %d",
		"Verify the endpoint path and credentials for the log source.",
		"核对该日志数据源的端点路径与凭据。"},
	{"MAS-4103", "LogsMalformed", SeverityError,
		"log source %q returned a malformed response: %s", "日志数据源 %q 返回了格式错误的响应：%s",
		"Confirm the URL points at a Loki-compatible HTTP API v1.",
		"确认该 URL 指向 Loki 兼容的 HTTP API v1。"},
	{"MAS-4104", "LogsQueryRejected", SeverityError,
		"log query rejected: %s", "日志查询被拒绝：%s",
		"The LogQL was refused by the server; check the knowledge pack's log pattern.",
		"服务端拒绝了该 LogQL；请检查知识包中的日志模式定义。"},
	{"MAS-4105", "LogsTruncated", SeverityWarn,
		"log result truncated at %d lines", "日志结果在 %d 行处被截断",
		"Narrow the window or raise telemetry.logs[].max_lines.",
		"收窄时间窗口，或提高 telemetry.logs[].max_lines。"},
	{"MAS-4201", "KubeForbidden", SeverityWarn,
		"Kubernetes denied read access to %s: %s", "Kubernetes 拒绝了对 %s 的读取：%s",
		"Grant the service account `get`/`list` on that resource; the run continues with a gap.",
		"为该 ServiceAccount 授予对应资源的 `get`/`list` 权限；本次运行将带缺口继续。"},
	{"MAS-4202", "KubeNoCredentials", SeverityWarn,
		"no Kubernetes credentials available for environment %q", "环境 %q 没有可用的 Kubernetes 凭据",
		"Set envs.<name>.kubeconfig, or run in-cluster with a service account.",
		"设置 envs.<name>.kubeconfig，或以带 ServiceAccount 的集群内方式运行。"},
	{"MAS-4203", "KubeUnreachable", SeverityError,
		"Kubernetes API server is unreachable: %s", "Kubernetes API Server 不可达：%s",
		"Check the server URL, CA bundle and network policy.",
		"检查 API Server 地址、CA 证书与网络策略。"},
	{"MAS-4204", "KubeNotFound", SeverityWarn,
		"Kubernetes object not found: %s", "Kubernetes 对象不存在：%s",
		"Check the namespace and selector on the target definition.",
		"检查目标定义中的命名空间与选择器。"},
	{"MAS-4205", "KubeMalformed", SeverityError,
		"Kubernetes API returned a malformed response: %s", "Kubernetes API 返回了格式错误的响应：%s",
		"Confirm the URL points at a Kubernetes API server.",
		"确认该 URL 指向 Kubernetes API Server。"},
	{"MAS-4210", "KubeExecDisabled", SeverityWarn,
		"in-container execution is disabled for environment %q",
		"环境 %q 已关闭容器内执行",
		"Set `envs.<name>.exec: true` (or remove the key) to let the guard decide per command. The switch can only narrow: it never widens what the guard allows.",
		"将 `envs.<name>.exec` 设为 true（或直接删除该键），即可交由护栏按命令判定。该开关只能收紧，绝不会放宽护栏允许的范围。"},
	{"MAS-4211", "KubeExecPodNotInTarget", SeverityError,
		"pod %q is not an instance of target %q",
		"Pod %q 不是目标 %q 的实例",
		"Exec is bound to the instances the target resolved to, so a run can never reach a pod outside it. Check the target's selector.",
		"exec 被绑定在目标解析出的实例集合上，因此一次运行永远无法触及集合之外的 Pod。请检查该目标的选择器。"},
	{"MAS-4212", "KubeExecUpgradeFailed", SeverityWarn,
		"could not open a remote-command stream to %s: %s",
		"无法与 %s 建立远程命令流：%s",
		"Usually RBAC: the credential needs `create` on `pods/exec`. It can also mean the pod is gone or an admission policy forbids exec.",
		"通常是 RBAC 问题：该凭据需要对 `pods/exec` 具备 `create` 权限。也可能是 Pod 已消失，或准入策略禁止 exec。"},
	{"MAS-4213", "KubeExecStreamMalformed", SeverityError,
		"the remote-command stream from %s was malformed: %s",
		"来自 %s 的远程命令流格式错误：%s",
		"The apiserver or an intermediary did not speak the v4.channel.k8s.io protocol. Check for a proxy that rewrites WebSocket traffic.",
		"apiserver 或中间设备并未遵循 v4.channel.k8s.io 协议。请检查是否有代理改写了 WebSocket 流量。"},
	{"MAS-4214", "KubeExecNoExitStatus", SeverityWarn,
		"the command in %s ended without reporting an exit status",
		"%s 中的命令结束时未报告退出状态",
		"The output is reported with its status recorded as unknown. It is not treated as success: a command whose outcome never arrived has not been shown to have worked.",
		"其输出会被照常报告，但状态记为未知。它不会被当作成功：一条结果从未到达的命令，并不能被认为已经成功。"},
	{"MAS-4301", "HostCommandFailed", SeverityWarn,
		"host command %q failed: %s", "主机命令 %q 执行失败：%s",
		"Check that the command exists and the process has permission to run it.",
		"确认该命令存在，且当前进程有权执行它。"},
	{"MAS-4302", "HostBinaryNotFound", SeverityWarn,
		"binary %q not found on PATH", "PATH 中未找到可执行文件 %q",
		"Install the tool in the image or on the host, or omit checks that need it.",
		"在镜像或主机上安装该工具，或跳过依赖它的检查。"},
	{"MAS-4303", "HostUnsupported", SeverityWarn,
		"host inspection %q is not supported on %s", "主机巡检 %q 在 %s 上不受支持",
		"This check is skipped; it is available on Linux hosts.",
		"该检查将被跳过；它仅在 Linux 主机上可用。"},
	{"MAS-4401", "SourceFellBackToMirror", SeverityWarn,
		"source for %q unreachable over the network; using local mirror %s", "%q 的源码网络不可达；改用本地镜像 %s",
		"Expected in air-gapped environments; verify the mirror matches the deployed version.",
		"离网环境下属预期行为；请确认镜像版本与部署版本一致。"},
	{"MAS-4402", "SourceUnavailable", SeverityWarn,
		"no source available for %q: %s", "%q 无可用源码：%s",
		"Configure source.repos or source.mirrors; source-based analysis is skipped.",
		"配置 source.repos 或 source.mirrors；基于源码的分析将被跳过。"},
	{"MAS-4403", "SourceRefNotFound", SeverityWarn,
		"source ref %q not found for %q", "%q 的源码 ref %q 不存在",
		"Check the target's version, or fetch the default branch instead.",
		"检查目标版本，或改为拉取默认分支。"},
	{"MAS-4404", "SourceSearchInvalid", SeverityError,
		"source search pattern is invalid: %s", "源码检索模式非法：%s",
		"Use a valid RE2 regular expression.",
		"请使用合法的 RE2 正则表达式。"},
	{"MAS-4405", "SourceToolMissing", SeverityWarn,
		"git is not available; source acquisition is disabled", "git 不可用；源码获取功能被禁用",
		"Install git in the image or on the host to enable source-based analysis.",
		"在镜像或主机上安装 git 以启用基于源码的分析。"},

	// ── 5xxx · knowledge & rules ────────────────────────────────────────────
	{"MAS-5001", "PackSchemaViolation", SeverityError,
		"knowledge pack %s is invalid at %s: %s", "知识包 %s 在 %s 处非法：%s",
		"Fix the pack against docs/en/knowledge-packs.md, then reload.",
		"对照 docs/zh/knowledge-packs.md 修正该包后重新加载。"},
	{"MAS-5002", "PackDuplicate", SeverityError,
		"duplicate knowledge pack id %q", "知识包 id %q 重复",
		"Two packs under knowledge.pack_dirs claim the same id, so which one wins would depend on directory order. Rename one, or delete the copy you no longer use. Overriding a built-in pack is supported and is not this error.",
		"knowledge.pack_dirs 下有两个知识包声明了相同的 id，谁生效将取决于目录顺序。请重命名其中之一，或删除不再使用的那份。覆盖内置知识包是被支持的，不属于此错误。"},
	{"MAS-5003", "PackNotFound", SeverityWarn,
		"no knowledge pack for middleware %q", "中间件 %q 没有对应的知识包",
		"Add a pack under knowledge.pack_dirs; analysis proceeds with generic checks only.",
		"在 knowledge.pack_dirs 下新增知识包；否则仅执行通用检查。"},
	{"MAS-5004", "PackVersionRangeInvalid", SeverityError,
		"knowledge pack %s has an invalid version range %q", "知识包 %s 的版本区间 %q 非法",
		"Use a range such as \">=5.0\", \"<7\", or \">=5.0 <8.0\".",
		"请使用形如 \">=5.0\"、\"<7\"、\">=5.0 <8.0\" 的区间。"},
	{"MAS-5005", "PackReadFailed", SeverityError,
		"knowledge pack %s could not be read: %s", "知识包 %s 无法读取：%s",
		"Check file permissions on the pack directory.",
		"检查知识包目录的文件权限。"},
	{"MAS-5010", "ExpressionCompile", SeverityError,
		"playbook %s step %s has an invalid expression: %s", "剧本 %s 的步骤 %s 表达式非法：%s",
		"Fix the expression; only step results and helper functions are in scope.",
		"修正该表达式；作用域内只有步骤结果与辅助函数。"},
	{"MAS-5011", "ExpressionType", SeverityError,
		"playbook %s step %s expression did not evaluate to a boolean: %s", "剧本 %s 的步骤 %s 表达式未求值为布尔：%s",
		"An `evaluate` expression must yield true or false.",
		"`evaluate` 表达式必须求值为 true 或 false。"},
	{"MAS-5012", "SignalUnknown", SeverityError,
		"playbook %s references unknown signal %q", "剧本 %s 引用了未知信号 %q",
		"Declare the signal under `signals:` in the same knowledge pack.",
		"在同一知识包的 `signals:` 下声明该信号。"},
	{"MAS-5013", "PlaybookBudgetExceeded", SeverityWarn,
		"playbook %s exceeded its step budget of %d", "剧本 %s 超出其步数预算 %d",
		"Split the playbook, or raise run.budget.max_steps.",
		"拆分该剧本，或提高 run.budget.max_steps。"},
	{"MAS-5014", "PlaybookStepInvalid", SeverityError,
		"playbook %s step %s is invalid: %s", "剧本 %s 的步骤 %s 非法：%s",
		"A step must declare exactly one of collect, evaluate or conclude.",
		"每个步骤必须且只能声明 collect、evaluate、conclude 之一。"},
	{"MAS-5015", "CheckNotPerformed", SeverityWarn,
		"playbook %s step %s was skipped: %s", "剧本 %s 的步骤 %s 已跳过：%s",
		"The check had no data to read, so its failure mode is neither confirmed nor ruled out. Check that the signal exists in this deployment.",
		"该检查没有可读取的数据，因此其故障模式既未被确认也未被排除。请确认该信号在当前部署中存在。"},
	{"MAS-5016", "RuleRangesOverlap", SeverityError,
		"two declarations of %s id %q have overlapping version ranges %q and %q (%s, %s)",
		"%s id %q 的两次声明版本区间重叠：%q 与 %q（%s、%s）",
		"A rule id may repeat only as version variants, and two variants must not both apply to any version. Narrow one of the ranges, or give the rules different ids.",
		"规则 id 只能以版本变体的形式重复，且任意两个变体不得同时适用于某个版本。请收窄其中一个区间，或给这两条规则不同的 id。"},
	{"MAS-5017", "NoVariantApplies", SeverityWarn,
		"%s %q has version variants but none applies to version %s",
		"%s %q 存在版本变体，但没有一个适用于版本 %s",
		"The pack covers this version but cannot place this rule in it. Widen one variant's range, or add one for this version.",
		"该知识包覆盖了这个版本，却无法为这条规则在其中定位。请放宽某个变体的区间，或为这个版本补一个变体。"},
	{"MAS-5018", "VersionUnknownForVariants", SeverityWarn,
		"%s %q has version-specific variants and the target's version is unknown",
		"%s %q 存在与版本相关的变体，而目标的版本未知",
		"Set `targets[].version` so the right variant can be chosen. Picking one without a version would query a metric name that may not exist and read its absence as data.",
		"请设置 `targets[].version`，以便选中正确的变体。在没有版本的情况下随便挑一个，会去查询一个可能并不存在的指标名，并把它的“查不到”当成数据来读。"},
	{"MAS-5019", "RulesNotApplicable", SeverityInfo,
		"%d rule(s) do not apply to version %s: %s",
		"有 %d 条规则不适用于版本 %s：%s",
		"Nothing was lost: these checks do not exist for this version. They are listed so a reader can tell version scoping from a check that failed to run.",
		"没有任何损失：这些检查对该版本本就不存在。列出它们，是为了让读者能区分“版本限定”与“没能跑起来的检查”。"},

	// ── 6xxx · storage ──────────────────────────────────────────────────────
	{"MAS-6001", "RunNotFound", SeverityError,
		"run %q not found", "运行记录 %q 不存在",
		"Run `mas runs` to list stored runs.",
		"执行 `mas runs` 查看已存储的运行记录。"},
	{"MAS-6002", "RunWriteFailed", SeverityError,
		"could not persist run %q: %s", "无法持久化运行记录 %q：%s",
		"Check that store.dir exists and is writable.",
		"确认 store.dir 存在且可写。"},
	{"MAS-6003", "RunCorrupt", SeverityError,
		"run %q is corrupt: %s", "运行记录 %q 已损坏：%s",
		"The record failed its integrity check and cannot be replayed.",
		"该记录未通过完整性校验，无法重放。"},
	{"MAS-6004", "RunStoreUnavailable", SeverityError,
		"run store is unavailable: %s", "运行存储不可用：%s",
		"Check store.type and store.dir.",
		"检查 store.type 与 store.dir。"},
	{"MAS-6010", "ObjectStoreConfigInvalid", SeverityError,
		"object store configuration is invalid at %s: %s", "对象存储配置在 %s 处非法：%s",
		"Correct the named path under `store.s3`. Endpoint, region and bucket are required, and the two credentials must both be set or both be empty — half a pair means you believe you configured access and did not.",
		"请修正 `store.s3` 下指出的配置路径。endpoint、region 与 bucket 为必填；两个凭据必须同时设置或同时留空 —— 只配一半，意味着你以为自己配好了访问权限，而其实没有。"},
	{"MAS-6011", "ObjectStoreRejected", SeverityError,
		"object store returned HTTP %d for %s: %s", "对象存储返回 HTTP %d（%s）：%s",
		"The S3 error code in the message says what to do: AccessDenied is a credential or policy problem, NoSuchBucket is the wrong bucket or region, SignatureDoesNotMatch is usually a clock more than a few minutes out.",
		"消息中的 S3 错误码说明了该怎么做：AccessDenied 是凭据或策略问题，NoSuchBucket 是桶或 region 弄错了，SignatureDoesNotMatch 通常是时钟偏差超过了几分钟。"},
	{"MAS-6012", "ObjectStoreUnreachable", SeverityError,
		"object store %s could not be reached: %s", "对象存储 %s 不可达：%s",
		"Check the endpoint and network policy. Runs still complete; they are reported as not persisted rather than silently lost.",
		"检查 endpoint 与网络策略。运行仍会完成；它们会被报告为“未持久化”，而不是被静默丢失。"},
	{"MAS-6013", "ObjectRecordMalformed", SeverityError,
		"stored record %s is malformed: %s", "存储中的记录 %s 格式错误：%s",
		"The object exists but is not a run record. Something other than this tool wrote to the prefix, or the object was truncated.",
		"该对象存在，但不是一条运行记录。要么有本工具之外的东西写入了这个前缀，要么该对象被截断了。"},
	{"MAS-6014", "RunTooManySteps", SeverityError,
		"run %s produced more steps than the key layout can order (%d)",
		"运行 %s 产生的步骤数超出了键布局可排序的范围（%d）",
		"This is far beyond the step budget and should not happen. The write is refused rather than wrapping around, because a silently reordered audit trail is worse than a missing one.",
		"这远超步数预算，本不应发生。写入被拒绝而不是回绕 —— 因为一份被静默重排的审计轨迹，比一份缺失的更糟。"},

	// ── 7xxx · API & CLI ────────────────────────────────────────────────────
	{"MAS-7001", "BadRequest", SeverityError,
		"bad request: %s", "请求非法：%s",
		"See docs/en/user-manual.md for the request schema.",
		"请求结构见 docs/zh/user-manual.md。"},
	{"MAS-7002", "MethodNotAllowed", SeverityError,
		"method %s not allowed on %s", "%s 方法不允许用于 %s",
		"Use the documented method for this endpoint.",
		"请对该端点使用文档规定的方法。"},
	{"MAS-7003", "ServerInternal", SeverityError,
		"internal server error: %s", "服务器内部错误：%s",
		"Check the server logs for the correlated run_id.",
		"根据关联的 run_id 检查服务端日志。"},
	{"MAS-7005", "ServerStartFailed", SeverityError,
		"server failed to start on %s: %s", "服务器在 %s 上启动失败：%s",
		"Check that the address is free and the process may bind it.",
		"确认该地址未被占用且进程有权绑定。"},
	{"MAS-7010", "APIUnauthenticated", SeverityError,
		"the API would bind %s with no authentication configured",
		"API 将在 %s 上监听，但未配置任何认证",
		"Anything that can reach that address could list your targets, read stored diagnoses and start new ones. Configure `server.auth.tokens`, or bind 127.0.0.1 and put your own proxy in front.",
		"任何能访问到该地址的东西，都可以列出你的目标、读取已存储的诊断，并发起新的诊断。请配置 `server.auth.tokens`，或改为监听 127.0.0.1 并在其前面放置你自己的代理。"},
	{"MAS-7011", "APIPlaintextCredentials", SeverityError,
		"the API would serve credentials over plaintext on %s",
		"API 将在 %s 上以明文传输凭据",
		"A bearer token on an unencrypted connection is a token on the wire. Set `server.tls.cert_file` and `key_file`, or set `server.tls.terminated_by_proxy: true` if something in front of this process terminates TLS.",
		"未加密连接上的 Bearer token，就是一份放在线路上的凭据。请设置 `server.tls.cert_file` 与 `key_file`；若本进程之前已有组件终止 TLS，则设置 `server.tls.terminated_by_proxy: true`。"},
	{"MAS-7012", "APICredentialMissing", SeverityError,
		"the request carried no usable credential",
		"请求未携带可用的凭据",
		"Send `Authorization: Bearer <token>` with a token configured under `server.auth.tokens`.",
		"请在请求中携带 `Authorization: Bearer <token>`，其中 token 需在 `server.auth.tokens` 下配置。"},
	{"MAS-7013", "APITokenScopeInvalid", SeverityError,
		"API token %q is unusable: %s", "API token %q 不可用：%s",
		"Every token must declare at least one scope, and every scope must be one this build knows. An ignored scope is an authorisation you believe you granted.",
		"每个 token 至少要声明一个 scope，且每个 scope 都必须是本版本认识的。一个被忽略的 scope，是一次你以为自己已经授出的授权。"},
	{"MAS-7014", "APIScopeMissing", SeverityError,
		"the credential lacks the %q scope this route requires",
		"该凭据缺少此路由所需的 %q scope",
		"Add the scope to this token under `server.auth.tokens[].scopes`, or call with a token that has it.",
		"请在 `server.auth.tokens[].scopes` 下给该 token 加上这个 scope，或改用已具备该 scope 的 token 调用。"},
	{"MAS-7015", "APITenantDenied", SeverityWarn,
		"credential %q may not act for tenant %q", "凭据 %q 无权代表租户 %q",
		"This appears in the audit log only. On the wire the request looks like an unknown target, because confirming that another tenant's target exists is the neighbour's information rather than the caller's.",
		"这只出现在审计日志中。在网络响应上，该请求看起来就是一个未知目标 —— 因为确认另一个租户的目标存在，泄露的是邻居的信息，而不是调用者的。"},
	{"MAS-7404", "NotFound", SeverityError,
		"not found: %s", "未找到：%s",
		"Check the identifier in the request path.",
		"检查请求路径中的标识符。"},

	// ── 8xxx · safety ───────────────────────────────────────────────────────
	{"MAS-8001", "MutatingRefused", SeverityError,
		"refused: %s would mutate the target environment", "已拒绝：%s 会变更目标环境",
		"MAS-Turbo is read-only by constitution; perform the action yourself if intended.",
		"MAS-Turbo 依据宪章只读；如确需执行，请由人工操作。"},
	{"MAS-8002", "CommandNotAllowed", SeverityError,
		"refused: %s is not on the read-only allow-list", "已拒绝：%s 不在只读白名单内",
		"Add the capability through a knowledge pack and a specification change, not at runtime.",
		"通过知识包与规格变更来新增该能力，而不是在运行期放行。"},
	{"MAS-8003", "PathNotAllowed", SeverityError,
		"refused: %s %s is not an allow-listed read path", "已拒绝：%s %s 不是白名单内的只读路径",
		"Only documented read endpoints may be called.",
		"只能调用文档中列明的只读端点。"},
	{"MAS-8005", "ArgumentRejected", SeverityError,
		"refused: argument %q rejected (%s)", "已拒绝：参数 %q 被拒（%s）",
		"Arguments may not contain shell metacharacters, traversal or mutating verbs.",
		"参数中不得包含 Shell 元字符、路径穿越或变更类动词。"},
	{"MAS-8006", "ToolNotRegistered", SeverityError,
		"refused: tool %q is not registered", "已拒绝：工具 %q 未注册",
		"Run `mas tools` to list the available capabilities.",
		"执行 `mas tools` 查看可用能力。"},
	{"MAS-8010", "CeilingExceeded", SeverityError,
		"refused: %s exceeds the configured ceiling (%s)", "已拒绝：%s 超出配置的上限（%s）",
		"Raise the ceiling in `safety:` only if you understand the resource cost.",
		"仅在确知资源代价的前提下，才在 `safety:` 中提高该上限。"},

	// ── 9xxx · internal ─────────────────────────────────────────────────────
	{"MAS-9001", "InvariantViolated", SeverityError,
		"internal invariant violated: %s", "内部不变量被破坏：%s",
		"This is a defect; please report it with the run record.",
		"这是缺陷；请附带运行记录反馈给我们。"},
	{"MAS-9002", "Unexpected", SeverityError,
		"unexpected internal error: %s", "未预期的内部错误：%s",
		"This is a defect; please report it with the run record.",
		"这是缺陷；请附带运行记录反馈给我们。"},
	{"MAS-9100", "CaseMalformed", SeverityError,
		"diagnostic case %s is malformed: %s", "诊断 case %s 格式错误：%s",
		"A case declares telemetry and the outcome a correct diagnosis reaches, both languages included. See docs/en/evaluation.md.",
		"case 需要声明遥测数据与一次正确诊断应得出的结果，且两种语言都要有。参见 docs/zh/evaluation.md。"},
	{"MAS-9101", "CaseModeUndeclared", SeverityError,
		"diagnostic case %s expects failure mode %q, which pack %s does not declare",
		"诊断 case %s 期望故障模式 %q，而知识包 %s 并未声明它",
		"A case can only assert conclusions the pack is able to reach; otherwise it fails forever and teaches nobody anything. Check the mode id against `mas packs --show`.",
		"case 只能断言该知识包有能力得出的结论；否则它会永远失败且毫无信息量。请用 `mas packs --show` 核对模式 id。"},
	{"MAS-9102", "CaseNoPack", SeverityError,
		"diagnostic case names middleware %q, which has no knowledge pack",
		"诊断 case 指向的中间件 %q 没有对应的知识包",
		"Ship a pack for that middleware, or point the case at one that exists.",
		"为该中间件提供知识包，或让该 case 指向一个已存在的中间件。"},
	{"MAS-9103", "CorpusRegressed", SeverityError,
		"the corpus regressed: %d case(s) missed and %d reached a conclusion the case rules out",
		"语料库出现回归：%d 个 case 漏判，%d 个得出了该 case 明确排除的结论",
		"Run `mas eval` to see which. A miss and a false conclusion are different failures: the first leaves an operator where they started, the second sends them somewhere wrong with confidence.",
		"执行 `mas eval` 查看具体是哪些。漏判与错误结论是两种不同的失败：前者让运维人员留在原地，后者自信地把他们送错方向。"},
	{"MAS-9104", "CaseDirUnreadable", SeverityError,
		"case directory %s cannot be read: %s", "case 目录 %s 无法读取：%s",
		"A mistyped --cases path would otherwise run the shipped corpus and report success, which is the one result that must never be produced by accident.",
		"若不报错，写错的 --cases 路径会去跑内置语料库并报告成功 —— 这正是绝不能被意外产生的结果。"},
	{"MAS-9105", "BaselineRegressed", SeverityError,
		"%d cell(s) regressed against the baseline: %s",
		"有 %d 个格子相对基线发生回归：%s",
		"A cell that was a hit no longer is. Run `mas eval --baseline <file>` to see what each one lost. If the change is intended, record it with --write-baseline so the new state is reviewed in a diff.",
		"某个原本命中的格子不再命中。执行 `mas eval --baseline <文件>` 查看每个格子失去了什么。若该变化是有意为之，请用 --write-baseline 记录，使新状态在 diff 中被评审。"},
	{"MAS-9106", "BaselineUnreadable", SeverityError,
		"baseline %s could not be read: %s", "基线 %s 无法读取：%s",
		"Point --baseline at a file written by --write-baseline. Treating an unreadable file as an empty baseline would make every cell look new, which reads as a clean comparison.",
		"请让 --baseline 指向由 --write-baseline 写出的文件。把无法读取的文件当作空基线，会让每个格子都看起来是新增的 —— 那读起来就像一次干净的比较。"},
	{"MAS-9107", "BaselineProviderMismatch", SeverityWarn,
		"the baseline was recorded under provider %q and this run used %q",
		"基线是在 provider %q 下记录的，而本次运行使用的是 %q",
		"Comparing across providers is what a model matrix is for; doing it without saying so is not. The comparison continues and this is disclosed with it.",
		"跨 provider 比较正是模型矩阵的意义所在；但不加说明地这么做则不是。比较会继续进行，并同时披露这一点。"},
}
