run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose
    - errorlint
    - gocritic
    - revive

linters-settings:
  misspell:
    locale: UK
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck, bodyclose, gocritic]
  max-issues-per-linter: 0
  max-same-issues: 0
